# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='learn',
            field=models.ManyToManyField(related_name='learn_languages', to='users.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='native',
            field=models.ManyToManyField(related_name='native_languages', to='users.Language'),
        ),
    ]
