# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import speakifyit.users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=speakifyit.users.models.user_directory_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token'),
        ),
    ]
