# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171110_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Middle name'),
        ),
    ]
