# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_languageskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='flag',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
