# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171123_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='native',
        ),
        migrations.AddField(
            model_name='user',
            name='native',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_language', to='users.Language'),
        ),
    ]
