# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_online'),
        ('chats', '0004_auto_20171127_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ContactRequest'),
        ),
    ]
